### ISSUE TITLE
trainer.py文件中保存peft_config时会出错

### ISSUE THREAD

**Issue by Mr-nnng** [OpenMOSS/CoLLiE#159]
File ".../python3.10/site-packages/collie/controller/trainer.py", line 618, in save_peft
    json.dumps(peft_config.__dict__),
  File ".../python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File ".../python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ".../python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File ".../python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable

**Comment by Mr-nnng** [comment]
config.peft_config: LoraConfig(peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path=None, revision=None, task_type=<TaskType.CAUSAL_LM: 'CAUSAL_LM'>, inference_mode=False, r=4, target_modules={'wqkv'}, lora_alpha=8, lora_dropout=0.05, fan_in_fan_out=False, bias='none', modules_to_save=[''], init_lora_weights=True, layers_to_transform=None, layers_pattern=None, rank_pattern={}, alpha_pattern={}, megatron_config=None, megatron_core='megatron.core', loftq_config={})

这里target_modules是集合，用json.dumps会出错

**Comment by KaiLv69** [comment]
抱歉回复比较晚，这个bug在PR https://github.com/OpenMOSS/CoLLiE/pull/166 里已经修复了。
