### ISSUE TITLE
No log information

### ISSUE THREAD

**Issue by BeastyZ** [OpenMOSS/CoLLiE#163]
Hi, when I trained the model, there was no log output information. Please fix this bug in time.

**Comment by KaiLv69** [comment]
Hi,
Which specific type of log are you looking for? It should be outputting the DeepSpeed logs, and after the start of the training loop, a progress bar should appear to indicate the training progress. 

By the way, if you are launching the task with srun, you might need to use `srun -u *** python -u train.py` to show the progress bar, depending on the srun configuration.

**Comment by BeastyZ** [comment]
I'm using the `srun` command without `-u` option. In this case, I can see the log information of ppl, but no progress bar of training. Maybe you are right, I will try the `srun -u *** python -u train.py`. Thanks a lot.
